name: ci

on:
  push:
    branches:
      - main

jobs:
  build:   
    runs-on: ubuntu-latest
    environment: prod
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Next
        run: docker build -t csmith661/react-fc .
          

      -
        name: Push Next
        run: docker push csmith661/react-fc
