name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
      NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
      EMAIL_SERVER_USER: "blank"
      EMAIL_SERVER_PASSWORD: "blank"
      EMAIL_SERVER_HOST: "BLANK"
      EMAIL_SERVER_PORT: 'BLANK'
      EMAIL_FROM: "BLANK"
      
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Next
        run: docker build -t csmith661/react-fc .

      -
        name: Push Next
        run: docker push csmith661/react-fc
